/**
 * Extracts the `abi` array from Hardhat artifacts and writes typed `as const`
 * TypeScript modules into frontend/src/abi/. Run after every contract change.
 *
 *   npx ts-node scripts/sync-abi.ts
 *
 * The `as const` cast is required for full type inference in viem/wagmi —
 * importing a plain JSON ABI loses the readonly tuple typing.
 */
import * as fs from "node:fs";
import * as path from "node:path";

const CONTRACTS = ["PaymentToken", "PropertyFactory", "PropertyShare"];
const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const OUT_DIR = path.join(__dirname, "..", "..", "frontend", "src", "abi");

fs.mkdirSync(OUT_DIR, { recursive: true });

for (const name of CONTRACTS) {
  const artifactPath = path.join(ARTIFACTS_DIR, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(artifactPath)) {
    console.error(`Artifact not found: ${artifactPath}`);
    process.exit(1);
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  const camelName = name.charAt(0).toLowerCase() + name.slice(1);
  const content =
    `// Auto-generated by contracts/scripts/sync-abi.ts — DO NOT EDIT BY HAND.\n` +
    `// Regenerate with: cd contracts && npm run sync:abi\n\n` +
    `export const ${camelName}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  const outPath = path.join(OUT_DIR, `${name}.ts`);
  fs.writeFileSync(outPath, content);
  console.log(`Wrote ${outPath}`);
}
